language: python

sudo: false
cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"

notifications:
  email:
    on_failure: change # [always|never|change] default: always

install:
  - pip install -U pip wheel
  - pip install coveralls
  - pip install git+git://github.com/ioam/param.git
  - pip install jinja2 tornado pyzmq matplotlib==1.4.2
  - pip install ipython==2
  - pip install pandas

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - nosetests --with-doctest --with-coverage --cover-package=holoviews -a '!optional'
  - cd doc/nbpublisher; chmod +x test_notebooks.py; ./test_notebooks.py
  - cd ../../; mv doc/Tutorials/.coverage ./.coverage.notebooks
  - coverage combine

after_success: coveralls
