language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

notifications:
  email:
    on_failure: change # [always|never|change] default: always

install:
  - pip install coveralls
  - pip install git+git://github.com/ioam/param.git
  - pip install jinja2 tornado pyzmq matplotlib==1.4.0
  - pip install ipython

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - nosetests --with-doctest --with-coverage --cover-package=holoviews

after_success: coveralls