trigger:
- master

jobs:

- job: 'unit_tests'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:

  - script: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: |
      conda config --set always_yes True
      conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
    displayName: 'Set up conda'

  - script: |
      doit env_create  --python=$(python.version)
      conda activate test-environment
      doit develop_install -c pyviz/label/dev -o unit_tests
      doit env_capture
    displayName: 'Install environment'

  - script: doit test_all_recommended
    displayName: 'Unit tests'
