trigger:
- master

jobs:

- job: 'unit_tests'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
      conda config --set always_yes True
      conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
    displayName: 'Set up conda'

  - script: |
      doit env_create  --python=$(python.version)
      conda activate test-environment
      doit develop_install $CHANS_DEV -o $HV_REQUIREMENTS
      doit env_capture
    displayName: 'Install environment'

  - script: doit test_all_recommended
    displayName: 'Unit tests'
